version: '3.8'

services:
  sqldb-app:
    build: .
    container_name: sqldb_app_container
    env_file:
      - .env
    ports:
      - "5005:5005"
    volumes:
      - .:/app
    command: python main.py
    restart: unless-stopped
